# Generated by Django 3.1.2 on 2021-04-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPGETRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('headers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='JSONPOSTRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('headers', models.JSONField()),
                ('sent_data', models.JSONField()),
                ('received_data', models.JSONField()),
            ],
        ),
    ]
